name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.1' 

      - name: Build binaries
        run: |
          mkdir -p builds
          for os in linux darwin; do
            for arch in amd64 arm64; do
              output_name="builds/memepulation-${os}-${arch}"
              version=${GITHUB_REF#refs/tags/} # Get the version from the tag
              GOOS=$os GOARCH=$arch go build -o $output_name -ldflags "-X main.version=${version}"
            done
          done

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }} 
          files: builds/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
