name: Build and Release

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.23.1"

            - name: Build binaries
              run: |
                  mkdir -p builds
                  for os in linux darwin; do
                    for arch in amd64 arm64; do
                      output_name="builds/memepulation-${os}-${arch}"
                      version=${GITHUB_REF#refs/tags/} 
                      GOOS=$os GOARCH=$arch go build -o $output_name -ldflags "-X main.version=${version}"
                    done
                  done

            - name: Create Release
              id: create_release
              run: |
                  TAG_NAME="${GITHUB_REF#refs/tags/}"
                  echo "::set-output name=TAG_NAME::${TAG_NAME}"

            - name: Publish Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ github.ref }} # This remains the full reference (e.g., refs/tags/v1.0.2)
                  release_name: ${{ steps.create_release.outputs.TAG_NAME }} # Use the clean tag name here
                  files: builds/*
                  prerelease: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use your token here

